Test/Test/Controllers/GoldenPondController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.Models.GoldenPond;
using Test.ViewModels;

namespace Test.Controllers
{
    public class GoldenPondController : Controller
    {        
        public ActionResult Test()
        {
            string stringCommands1 = "PFPFPFPFF";                                            
            DuckState stateStart1 = new DuckState() { X = 1, Y = 2, Orientation = Orientation.N };
            DuckState stateEnd1 = new DuckState(stateStart1);
            stateEnd1.FollowCommands(stringCommands1);

            string stringCommands2 = "FFSFFSFSSF";
            DuckState stateStart2 = new DuckState() { X = 3, Y = 3, Orientation = Orientation.E };
            DuckState stateEnd2 = new DuckState(stateStart2);
            stateEnd2.FollowCommands(stringCommands2);

            IEnumerable<GoldenPondViewModel> vm = new List<GoldenPondViewModel>() {

                new GoldenPondViewModel() {                  
                    StartState = stateStart1,
                    EndState = stateEnd1,
                    Commands = stringCommands1
                },
                new GoldenPondViewModel() {
                    StartState = stateStart2,
                    EndState = stateEnd2,
                    Commands = stringCommands2
                },
            };

            return View(vm);
        }
    }
}

Test/Test/Controllers/MessagesDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.ViewModels;
using Test.Repositories.MessagesDB;
using Test.Models.MessagesDB;

namespace Test.Controllers
{
    public class MessagesDBController : Controller
    {
        private IMessagesDBRepository<Person, int> _repo;

        public MessagesDBController(IMessagesDBRepository<Person, int> repo)
       {
           _repo = repo;
       }

        public ActionResult TestEF()
        {
             var domains = _repo.GetDomains();
             var emailAddressesWithPersonNames = _repo.GetEmailAddressesWithPersonNames();
             var emailsCountForDomains = _repo.GetEmailsCountForDomains();

             var vm = new MessagesDBViewModel()
             {
                 Title = "EF",
                 Domains = domains,
                 EmailAddressesWithPersonNames = emailAddressesWithPersonNames,
                 EmailsCountForDomains = emailsCountForDomains,
             };
            return View("Test",vm);
        }

        public ActionResult TestSQL()
        {
            var domains = _repo.GetDomainsSQL();
            var emailAddressesWithPersonNames = _repo.GetEmailAddressesWithPersonNamesSQL();
            var emailsCountForDomains = _repo.GetEmailsCountForDomainsSQL();

            var vm = new MessagesDBViewModel()
            {
                Title = "SQL",
                Domains = domains,
                EmailAddressesWithPersonNames = emailAddressesWithPersonNames,
                EmailsCountForDomains = emailsCountForDomains,
            };
            return View("Test", vm);
        }
    }
}

Test/Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tiny Url Application</title> 
    
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css">  
    <link rel="stylesheet" href="/content/site.css">
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
             
                <a href="#" class="navbar-brand"> <span class="glyphicon glyphicon-cog"></span></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("MessagesDB-EF", "TestEF", "MessagesDB")</li>
                    <li>@Html.ActionLink("MessagesDB-SQL", "TestSQL", "MessagesDB")</li>
                    <li>@Html.ActionLink("Golden Pond", "Test", "GoldenPond")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container" style="padding-top:30px;">
        <div class="row" style="padding-top:30px;">
            <div class="col-xs-12">
                <div id="main-content">
                    @RenderSection("MainContent", required: false)
                </div>
            </div>
        </div>
    </div>
    @RenderBody()   
    <footer>
        <div class="container">
            <div class="row" style="margin-top:25px;">
                <div class="col-xs-12 text-center">          
                    @RenderSection("FooterContent", required: false)
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="http://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/js/bootstrap-dialog.min.js"></script>
    @RenderSection("scripts", required: false)
  </body>
</html>


    